INSERT INTO element_subtype VALUES (2007, 4, 'UTC', 'UTC', 'UTC');
INSERT INTO element_subtype VALUES (2008, 4, 'PST', 'America/Tijuana', 'Pacific Standard Time (Mexico)');
INSERT INTO element_subtype VALUES (2009, 4, 'MST', 'America/Denver', 'Mountain Standard Time (Mexico)');
INSERT INTO element_subtype VALUES (2010, 4, 'CST', 'America/Mexico_City', 'Central Standard Time (Mexico)');
INSERT INTO element_subtype VALUES (2011, 4, 'SAPST', 'America/Lima', 'SA Pacific Standard Time');
INSERT INTO element_subtype VALUES (2012, 4, 'CBST', 'America/Cuiaba', 'Central Brazilian Standard Time');
INSERT INTO element_subtype VALUES (2013, 4, 'ART', 'America/Argentina/Buenos_Aires', 'Argentina Standard Time');
INSERT INTO element_subtype VALUES (2014, 4, 'MVST', 'America/Montevideo', 'Montevideo Standard Time');
INSERT INTO element_subtype VALUES (2015, 4, 'PSAST', 'America/Santiago', 'Pacific SA Standard Time');
INSERT INTO element_subtype VALUES (2016, 4, 'MOST', 'Africa/Casablanca', 'Morocco Standard Time');
INSERT INTO element_subtype VALUES (2017, 4, 'GMT', 'Europe/London', 'GMT Standard Time');
INSERT INTO element_subtype VALUES (2018, 4, 'GST', 'Atlantic/Reykjavik', 'Greenwich Standard Time');
INSERT INTO element_subtype VALUES (2019, 4, 'WET', 'Europe/Amsterdam', 'W. Europe Standard Time');
INSERT INTO element_subtype VALUES (2020, 4, 'CET', 'Europe/Prague', 'Central Europe Standard Time');
INSERT INTO element_subtype VALUES (2021, 4, 'RST', 'Europe/Paris', 'Romance Standard Time');
INSERT INTO element_subtype VALUES (2022, 4, 'CEST', 'Europe/Warsaw', 'Central European Standard Time');
INSERT INTO element_subtype VALUES (2023, 4, 'GTBST', 'Europe/Athens', 'GTB Standard Time');
INSERT INTO element_subtype VALUES (2024, 4, 'EGST', 'Africa/Cairo', 'Egypt Standard Time');
INSERT INTO element_subtype VALUES (2025, 4, 'EEST', 'Europe/Minsk', 'E. Europe Standard Time');
INSERT INTO element_subtype VALUES (2026, 4, 'SAST', 'Africa/Harare', 'South Africa Standard Time');
INSERT INTO element_subtype VALUES (2027, 4, 'EET', 'Europe/Helsinki', 'FLE Standard Time');
INSERT INTO element_subtype VALUES (2028, 4, 'ISST', 'Asia/Jerusalem', 'Israel Standard Time');
INSERT INTO element_subtype VALUES (2029, 4, 'ABST', 'Asia/Kuwait', 'Arab Standard Time');
INSERT INTO element_subtype VALUES (2030, 4, 'ARBST', 'Asia/Muscat', 'Arabian Standard Time');
INSERT INTO element_subtype VALUES (2031, 4, 'IST', 'Asia/Kolkata', 'India Standard Time');
INSERT INTO element_subtype VALUES (2032, 4, 'SLT', 'Asia/Colombo', 'Sri Lanka Standard Time');
INSERT INTO element_subtype VALUES (2033, 4, 'CHST', 'Asia/Chongqing', 'China Standard Time');
INSERT INTO element_subtype VALUES (2034, 4, 'SNST', 'Asia/Singapore', 'Singapore Standard Time');
INSERT INTO element_subtype VALUES (2035, 4, 'AWST', 'Australia/Perth', 'W. Australia Standard Time');
INSERT INTO element_subtype VALUES (2036, 4, 'TST', 'Asia/Tokyo', 'Tokyo Standard Time');
INSERT INTO element_subtype VALUES (2037, 4, 'KST', 'Asia/Seoul', 'Korea Standard Time');
INSERT INTO element_subtype VALUES (2038, 4, 'CAUST', 'Australia/Adelaide', 'Cen. Australia Standard Time');
INSERT INTO element_subtype VALUES (2039, 4, 'EAST', 'Australia/Brisbane', 'E. Australia Standard Time');
INSERT INTO element_subtype VALUES (2040, 4, 'NZST', 'Pacific/Auckland', 'New Zealand Standard Time');

